export default {
    products: [
        {
            _id:'1',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'2',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'3',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'4',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'5',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'6',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'7',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
        {
            _id:'8',
            name:"Nogi do stolika",
            image:"../images/productsImage/nogi/NogiDoStolika.png",
            price:"160",
            cointInStock:"10",
        },
    ],
};